server:
  port: 8084

myRoom:
  platformFeePercentage: 2
  frontendUrl: http://localhost:3000

# Stripe API
stripe:
  api:
    secret-key: secret-key
  endpointSecret: endpointSecret


services:
  booking-service:
    id: BOOKING-SERVICE
    v1:
      api: /api/v1/booking-service
      name: BOOKING-SERVICE_V1

  payment-service:
    id: PAYMENT-SERVICE
    v1:
      api: /api/v1/payment-service
      name: PAYMENT-SERVICE_V1

  organization-pay:
    id: ORGANIZATION-PAY-SERVICE
    v1:
      api: /api/v1/organizationpay
      name: ORGANIZATION-PAY-SERVICE_V1

  room-service:
    id: ROOM-SERVICE
    v1:
      api: /api/v1/room-service
      name: ROOM-SERVICE_V1

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:mysql://myroomawsdb.c3esb8f8pxjo.us-east-1.rds.amazonaws.com/myroom
    username: admin
    password: Devops898

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ec2-34-234-196-243.compute-1.amazonaws.com:9092
    advertised:
      host:
        name: 34.234.196.243

  main:
    allow-circular-references: true


# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://3.229.47.37:8761/eureka
